import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { signIn } from '../services/api';

export default function LoginPage() {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const navigate = useNavigate();
  async function handleSubmit(event: React.FormEvent) { event.preventDefault(); setError(''); setLoading(true); try { await signIn(email, password); navigate('/dashboard'); } catch { setError('Não foi possível entrar. Confira seus dados e se a API está em execução.'); } finally { setLoading(false); } }
  return <div className="flex min-h-screen items-center justify-center bg-[radial-gradient(circle_at_top,_rgba(124,77,255,0.18),_transparent_28%),_linear-gradient(180deg,_#060517_0%,_#0c0828_100%)] px-4 py-10 text-white"><div className="w-full max-w-md rounded-[28px] border border-white/10 bg-white/5 px-8 py-10 shadow-[0_24px_80px_rgba(15,10,40,0.24)] backdrop-blur-xl"><p className="text-sm uppercase tracking-[0.32em] text-purple-300/70">4Core</p><h1 className="mt-3 text-3xl font-semibold">Acesso à plataforma</h1><p className="mb-8 mt-3 text-sm text-slate-300">Entre para acompanhar a operação, os clientes e a saúde financeira da empresa.</p><form className="space-y-5" onSubmit={handleSubmit}><label className="block text-sm text-slate-300">E-mail<input required type="email" className="mt-2 w-full rounded-2xl border border-white/10 bg-white/5 px-4 py-3 text-white outline-none focus:border-violet-400/70" placeholder="nome@empresa.com" value={email} onChange={(e) => setEmail(e.target.value)} /></label><label className="block text-sm text-slate-300">Senha<input required type="password" className="mt-2 w-full rounded-2xl border border-white/10 bg-white/5 px-4 py-3 text-white outline-none focus:border-violet-400/70" placeholder="••••••••" value={password} onChange={(e) => setPassword(e.target.value)} /></label>{error && <p className="rounded-2xl bg-rose-500/15 px-4 py-3 text-sm text-rose-100">{error}</p>}<button disabled={loading} className="w-full rounded-2xl bg-gradient-to-r from-violet-500 to-fuchsia-500 px-4 py-3 font-semibold text-white disabled:cursor-wait disabled:opacity-70">{loading ? 'Entrando...' : 'Entrar'}</button></form></div></div>;
}
